### ISSUE TITLE
People confuse github team name for github user name - more clarification may be required in instruction 3

### ISSUE THREAD

**Issue by JessRudder** [learn-co-curriculum/fe-code-along-3#1]
Instruction 3 is confusing to some students as they think their "github team name" is their "github user name"

"To get the most up to date starting code used for this exercise create a new remote called upstream ♥ git remote add upstream git@github.com:learn-co-students/fe-exceptional-realty-<insert your github team name here>.git (example batch: fe-0415 or ruby-0515)."

We give examples, but, I'm not sure they're that meaningful (especially using the term batch).

Perhaps it would be helpful to tell them where to find this information (e.g. it shows up at the end of the name of all the labs you've cloned so far).

**Comment by sammarcus** [comment]
@JessRudder +1

**Comment by sammarcus** [comment]
@JessRudder Do you know how those spawn off (..?) repos are being generated? I'm pretty sure there isn't one for web-0915, I had to add a student to this one since she couldn't pull down elsewhere. I may raise a separate issue

**Comment by AnnJohn** [comment]
@jongrover Can you update the ReadMe? Would by 8/24 work?

**Comment by AnnJohn** [comment]
@jongrover  ^^

**Comment by jongrover** [comment]
This issue is no longer relevant. The lab is now forked, cloned, by students like the others. The step 3 they are referring to no longer exists in the README.
